# Generated by Django 4.2.16 on 2025-05-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animateur',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='animateur',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='animateur',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='animateur',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
