# Generated by Django 4.2.16 on 2025-05-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_animateur_facebook_animateur_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='date_diffusion',
        ),
        migrations.AddField(
            model_name='programme',
            name='jour',
            field=models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
