# Generated by Django 5.0.6 on 2024-07-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('Culture', 'Culture'), ('Découverte', 'Découverte'), ('Économie', 'Économie'), ('Sports', 'Sports'), ('Tendance', 'Tendance'), ('Liste de Lecture', 'Liste de Lecture'), ('Marque-Page', 'Marque-Page')], default='Culture', max_length=20),
        ),
    ]
