# Generated by Django 5.0.6 on 2024-07-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_podcast_audio_file_podcast_auteur_video_auteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
